//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectibleData
    {
        public System.Guid ID { get; set; }
        public System.Guid RoomID { get; set; }
        public string WikiCode { get; set; }
        public int SerialNumber { get; set; }
        public string Wikidata { get; set; }
        public string Image { get; set; }
        public string Label { get; set; }
        public string Creator { get; set; }
        public string DateOfEstab { get; set; }
        public string Nature { get; set; }
        public string RegisterNumber { get; set; }
        public string JocondeEncoding { get; set; }
        public string AtlasIndexNumber { get; set; }
        public int Status { get; set; }
    
        public virtual RoomData RoomData { get; set; }
    }
}
