//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExhibitionActivityData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExhibitionActivityData()
        {
            this.PackageItineraries = new HashSet<PackageItinerary>();
            this.HallDatas = new HashSet<HallData>();
        }
    
        public System.Guid ID { get; set; }
        public string ActivityCode { get; set; }
        public string DisplayTitle { get; set; }
        public string Author { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int ExtensionClassify { get; set; }
        public int VisitLimitationPerDay { get; set; }
        public decimal SuggestVisitingHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageItinerary> PackageItineraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallData> HallDatas { get; set; }
    }
}
