//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupRegistration()
        {
            this.GroupRegistrationVisitors = new HashSet<GroupRegistrationVisitor>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PackageID { get; set; }
        public int Minors { get; set; }
        public int Adults { get; set; }
        public decimal Amount { get; set; }
        public string VisitLanguage { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.TimeSpan> VisitStartTime { get; set; }
        public Nullable<System.TimeSpan> VisitEndTime { get; set; }
        public System.Guid TravelAgencyUserDataID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
        public int Status { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual TravelAgencyUserData TravelAgencyUserData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRegistrationVisitor> GroupRegistrationVisitors { get; set; }
    }
}
