//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRegistrationVisitor
    {
        public System.Guid GroupRegistrationID { get; set; }
        public int No { get; set; }
        public string VisitorID { get; set; }
        public string VisitorName { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string EMail { get; set; }
        public Nullable<int> FreeID { get; set; }
        public string Note { get; set; }
    
        public virtual FreeQualification FreeQualification { get; set; }
        public virtual GroupRegistration GroupRegistration { get; set; }
    }
}
