//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.GroupRegistrations = new HashSet<GroupRegistration>();
            this.PackageItineraries = new HashSet<PackageItinerary>();
        }
    
        public System.Guid ID { get; set; }
        public string PackageName { get; set; }
        public string Features { get; set; }
        public string VisitTime { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<double> FeePerPerson { get; set; }
        public Nullable<int> Maximum { get; set; }
        public string IsValid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRegistration> GroupRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageItinerary> PackageItineraries { get; set; }
    }
}
