//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageItinerary
    {
        public System.Guid PackageID { get; set; }
        public System.Guid ExhibitionActivityDataID { get; set; }
        public int VisitOrder { get; set; }
    
        public virtual ExhibitionActivityData ExhibitionActivityData { get; set; }
        public virtual Package Package { get; set; }
    }
}
