//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomData()
        {
            this.CollectibleDatas = new HashSet<CollectibleData>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid HallID { get; set; }
        public string RoomName { get; set; }
        public string CommonsCategory { get; set; }
        public int Floor { get; set; }
        public string Extension { get; set; }
        public int Status { get; set; }
        public string SpecialOpenNote { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectibleData> CollectibleDatas { get; set; }
        public virtual HallData HallData { get; set; }
    }
}
