//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffData()
        {
            this.HallWithStaffs = new HashSet<HallWithStaff>();
        }
    
        public System.Guid AccountID { get; set; }
        public string EmployeeNumber { get; set; }
        public string JobTitle { get; set; }
        public string PreferedLanguage { get; set; }
    
        public virtual AccountData AccountData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallWithStaff> HallWithStaffs { get; set; }
    }
}
