//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouvreGRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelAgencyUserData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelAgencyUserData()
        {
            this.GroupRegistrations = new HashSet<GroupRegistration>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid AccountID { get; set; }
        public System.Guid TravelAgencyID { get; set; }
        public int Type { get; set; }
    
        public virtual AccountData AccountData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRegistration> GroupRegistrations { get; set; }
        public virtual TravelAgencyData TravelAgencyData { get; set; }
    }
}
